#!/usr/bin/env python
"""A script to handle any events passed to STDIN."""

import sys

from gotoalert.alert import event_handler


if __name__ == '__main__':
    payload = sys.stdin.buffer.read()
    event_handler(payload)
