#!/usr/bin/env python3
"""A script to handle any events passed to STDIN."""

import sys

from gtecs.alert.events import Event
from gtecs.alert.handler import event_handler


if __name__ == '__main__':
    payload = sys.stdin.buffer.read()
    event = Event.from_payload(payload)
    event_handler(event)
