#!/usr/bin/env python
"""A simple test script for GOTO-alert."""

import os

from gotoalert.alert import event_handler
from gotoalert.events import Event

import pkg_resources


if __name__ == '__main__':
    # used for local testing
    data_dir = pkg_resources.resource_filename('gotoalert', 'data')
    testdata_path = os.path.join(data_dir, 'ivo__nasa.gsfc.gcn_SWIFTBAT_GRB_Pos_813449030')
    with open(testdata_path, "rb") as f:
        payload = f.read()
        event = Event(payload)
        event_handler(event)
