#!/usr/bin/env python

import os
import sys
import pkg_resources
import voeventparse as vp

from gotoalert.alert import event_handler


if __name__ == '__main__':
    # used for local testing
    data_dir = pkg_resources.resource_filename('gotoalert', 'data')
    testdata_path = os.path.join(data_dir, 'ivo__nasa.gsfc.gcn_SWIFTBAT_GRB_Pos_813449030')
    with open(testdata_path, "rb") as f:
        v = vp.load(f)

    event_handler(v)
